name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v3
    - name: Checkout submodules
    - uses: derzwerggimli/solana_helper@master
    - name: Build
    - run: cargo build --release --verbose
